[package]
name = "pastebuff-server"
version = "0.1.0"
edition = "2021"

[dependencies]
colog = "1.3.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
